### PR TITLE
Fix geom polygon compatibility

### LINKED ISSUE #26: facet_wrap not working
When trying to use `facet_wrap` only one facet appears with the rink

image

```
data <- tibble(x = c(0, 22, -22, 41),
               y = c(50, 25, 85, 41.3),
               group = c("shot", "shot", "goal", "goal"))

geom_hockey("NHL", "ozone", rotation = 90) +
  geom_point(data = data, aes(x = x, y = y, color = group)) +
  facet_wrap(~group)
```

### PR DESCRIPTION
**Pull request by mrcaseb**
fixes #26 

polygons in `add_feature` were drawn by a call to `geom_polygon` with empty datasets. x and y "aesthetics" were assigned values from actual data frames. This messed up facets because ggplot2 "forgot" the data. 

This PR fixes that problem. I do not know if I introduce new problems so @rossdrucker should test and make sure I don't break anything else. However, the below reprex shows that the bug in #26 is fixed. 

``` r
library(tibble)
library(ggplot2)
library(sportyR)

data <- tibble(x = c(0, 22, -22, 41),
               y = c(50, 25, 85, 41.3),
               group = c("shot", "shot", "goal", "goal"))

geom_hockey("NHL", "ozone", rotation = 90) +
  geom_point(data = data, aes(x = x, y = y, color = group)) +
  facet_wrap(~group)
```

<sup>Created on 2023-06-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/plot-helpers.R [hunk 1]
```diff
@@ -59,6 +59,7 @@ create_plot_base <- function(plot_background = NULL) {
 #' @return A \code{ggplot2} instance with the feature added to it
 #'
 #' @keywords internal
+#' @importFrom rlang .data
```
Comment (rossdrucker) [inline R/plot-helpers.R:62]: @mrcaseb just added this (and subsequent `.data${{variable}}` below) to avoid notes. Otherwise looks good!

**Review by rossdrucker — APPROVED** [review]
